CREATE TABLE PERSON (
  per_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  per_name VARCHAR2(100) NOT NULL,
  per_whatsapp VARCHAR2(20),
  per_email VARCHAR2(100),
  per_password VARCHAR2(255),
  per_role VARCHAR2(20),
  per_created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX ux_per_email ON person (per_email);

CREATE TABLE REGION (
  reg_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  reg_name VARCHAR2(100) NOT NULL,
  reg_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  reg_created_by NUMBER REFERENCES person(per_id)
);
CREATE UNIQUE INDEX ux_reg_name ON region (reg_name);

CREATE TABLE road (
  roa_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  roa_address VARCHAR2(200) NOT NULL,
  roa_speed_limit NUMBER(5,2) NOT NULL,
  roa_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  roa_updated_at TIMESTAMP
);

CREATE TABLE criterion (
  cri_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cri_name VARCHAR2(100) NOT NULL,
  cri_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  cri_created_by NUMBER REFERENCES person(per_id)
);
CREATE UNIQUE INDEX ux_cri_name ON criterion (cri_name);

CREATE TABLE protocol (
  pro_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  pro_name VARCHAR2(100) NOT NULL,
  pro_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  pro_created_by NUMBER REFERENCES person(per_id)
);
CREATE UNIQUE INDEX ux_pro_name ON protocol (pro_name);

CREATE TABLE camera (
  cam_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cam_latitude NUMBER(9,6) NOT NULL,
  cam_longitude NUMBER(9,6) NOT NULL,
  cam_active NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0, 1)),
  cam_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  cam_updated_at TIMESTAMP,
  roa_id NUMBER NOT NULL REFERENCES road(roa_id)
);
CREATE INDEX ix_camera_roa_id ON camera(roa_id);

CREATE TABLE criterion_level (
  cl_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cl_level NUMBER(5) NOT NULL,
  cl_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  cl_created_by NUMBER REFERENCES person(per_id),
  cri_id NUMBER NOT NULL REFERENCES criterion(cri_id)
);
CREATE INDEX ix_criterion_level_cri_id ON criterion_level(cri_id);

CREATE TABLE alert (
  ale_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ale_level NUMBER(5),
  ale_message VARCHAR2(255),
  ale_conclusion VARCHAR2(255),
  ale_source_type VARCHAR2(30),
  ale_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  ale_closed_at TIMESTAMP,
  ale_created_by NUMBER REFERENCES person(per_id),
  ale_assigned_to NUMBER REFERENCES person(per_id),
  cam_id NUMBER REFERENCES camera(cam_id),
  cri_id NUMBER NOT NULL REFERENCES criterion(cri_id),
  rc_id NUMBER REFERENCES root_cause(rc_id)
);
CREATE INDEX ix_alert_created_by ON alert(ale_created_by);
CREATE INDEX ix_ale_assigned_to ON alert(ale_assigned_to);
CREATE INDEX ix_alert_cam_id ON alert(cam_id);
CREATE INDEX ix_alert_cri_id ON alert(cri_id);
CREATE INDEX ix_alert_rc_id ON alert(rc_id);

CREATE TABLE reading (
  rea_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  rea_created_at TIMESTAMP NOT NULL,
  rea_vehicle_type VARCHAR2(30),
  rea_speed NUMBER(5,2),
  rea_plate VARCHAR2(10),
  cam_id NUMBER NOT NULL REFERENCES camera(cam_id)
);
CREATE INDEX ix_reading_camera_id ON reading(cam_id);

CREATE TABLE detected_incident (
  di_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  di_incident_type VARCHAR2(80),
  di_created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  di_created_by NUMBER REFERENCES person(per_id),
  ale_id NUMBER NOT NULL REFERENCES alert(ale_id)
);
CREATE INDEX ix_incident_ale_id ON detected_incident(ale_id);
CREATE INDEX ix_incident_per_id ON detected_incident(di_created_by);

CREATE TABLE alert_log (
  al_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  al_created_at TIMESTAMP,
  al_previous_level NUMBER(5),
  al_new_level NUMBER(5),
  al_closed_at TIMESTAMP,
  ale_id NUMBER NOT NULL REFERENCES alert(ale_id),
  reg_id NUMBER REFERENCES region(reg_id)
);

CREATE INDEX ix_alert_log_ale_id ON alert_log(ale_id);
CREATE INDEX ix_alert_log_reg_id ON alert_log(reg_id);

