name: PR Description

on:
  pull_request:
    types:
      - opened

jobs:
  set-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR Description
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const prNumber = context.payload.pull_request.number;
            // Default PR description
            const description = `
### Description
This PR was created to ...
[Card](link here)

### Business rules
- N/A

### How to test
- Step 1
`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: description,
            });